### ISSUE TITLE
Collecting information from component maintainers

### ISSUE THREAD

**Issue by francescamarano** [francescamarano/release-model-wg#1]
# What I did for 5.4

1. Create a Google Spreadsheet with the list of Component and their Maintainers.
2. Create a group DM with maintainers for each component.
3. Come up with the text to send them: it needs to be clear what I am asking for.
4. Collecting the replies into the same Google Spreadsheet
    4.1 Not all replies are straightforward, so sometimes there is going to be some back and forth, and some recapping of the things said
    4.2 Understanding which items are at a stage that makes them reasonable candidates for features that will _really_ be ready for the release
    4.3 Understanding which items are _ongoing/maintenance/not exciting_ and which are _ready/exciting enough to be in the announcement post_
5. Preparing a draft of the planning post based on these replies

# Pain Points
- Having to open many group DMS - time-consuming
- Not having enough technical knowledge to evaluate 4.2 and 4.3 
- Not getting replies from some components: at this round, I didn't have time to ping them again, but it should be done.
- My lack of understanding of the different types of "items" in the pipeline: features vs bugs (relates also to something expressed by some maintainers, see belove, last bullet point)

# Feedback collected + my impressions
- Maintainers not having been involved for a while and not having a clear picture of what is going on in their component
- Maintainers not being 100% sure what is their role
- Maintainers not being sure how much weight to they carry: if something is ready or they are ready to commit to work on it so it will be ready for the next release, does it go in by default?
- Maintainers thinking that they need a committer in their Component to move things forward more quickly
- Lack of the main scope for release from leadership makes it harder for maintainers to pick what to focus on amongst the many tickets they have and the many ideas/dreams they have

# Time spent
- Around 4 hours for items 1 to 3
- Around 4 hours for item 4 - this is done in different moments since everyone is replying at different times
- Around 1 hour to add them to the post, refine the phrasing, check with other people to see that it is clear, etc...

**Comment by marybaum** [comment]
I'm in for Steps 2 and 3, and we can rope in people with the requisite tech knowledge for step 4.

**Comment by noisysocks** [comment]
> Come up with the text to send them: it needs to be clear what I am asking for.

What did/do you ask for?

> Lack of the main scope for release from leadership makes it harder for maintainers to pick what to focus on amongst the many tickets they have and the many ideas/dreams they have

This is interesting! What did/do the component maintainers that you spoke to end up doing? Were/are they able to name some tickets to focus on ("bottom up"), or did/does project leadership get involved ("top down")?

**Comment by kittenkamala** [comment]
@francescamarano is it possible for you to share the spreadsheet you had previously made? I'm wondering if a google form would be easier for people to provide feedback through rather than a DM. Something like this? https://forms.gle/LUyt8sSuvkpK2afq9

**Comment by francescamarano** [comment]
Had notifications turned off 🤷‍♀ 
@marybaum agreed, but the model of pinging ad personam is still not very scalable

@noisysocks 
The message was 

> Hello XX Maintainers!
> I am collecting info to put together a plan for WordPress 5.4
> ETA March 31st
> I did run some possible scenarios to have it happen before that but with the end of the year holidays it doesn’t seem likely
> I would like to ask you for a list of features that are likely to be done in time for the release
> The idea is to collect the info from all the components and see if there is a reasonable set of 4-5 that we can focus on
> Let me know
> Thanks!

Regarding the lack of direction: some have enough ideas/appetite/motivation to move things on even if it's not within the general scope we are all working towards (Full Site Editing), others not so much, especially if they feel or know that their component is not a priority.

@kittenkamala I love the idea of the Google Form! We could just ping everyone with `@maintainers ` weekly and see the replies trickling in.

**Comment by francescamarano** [comment]
Since I think the reporting on this issue is pretty much done, and now we are moving to proposal phase, we could mark this as done?

**Comment by kittenkamala** [comment]
Agreed
