### ISSUE TITLE
Publish field guide

### ISSUE THREAD

**Issue by noisysocks** [francescamarano/release-model-wg#18]
This issue is for researching this item in [the spreadsheet](https://docs.google.com/spreadsheets/d/1KZ4dZyhco3sbYQ3LGpNbsu7HC4WcTM6SLQHt6Ggjz-Q/edit#gid=0):

> Publish Field Guide

**Comment by francescamarano** [comment]
I'll ask @jeffreypaul to chime in :)

**Comment by jeffpaul** [comment]
So far this is what's documented on the [`Releasing Major Versions` page](https://make.wordpress.org/core/handbook/about/release-cycle/releasing-major-versions/):
> `Pre Release Candidate`
> - Publish the [Field Guide](https://make.wordpress.org/core/tag/field-guide/) on Make/Core, highlighting the developer-focused changes in the release. This should include the devnotes published before Beta.
> - All Plugin Authors (in the wp.org repo) should be emailed, letting them know to test their plugins for compatibility with the release. The email should link them to the Field Guide. [Contact the Plugin Team Rep to coordinate](https://make.wordpress.org/updates/team-reps/) or publish the draft release email on the [Plugin Review Team’s make site](https://make.wordpress.org/pluginrepo) ([sample from 5.3 here](https://make.wordpress.org/pluginrepo/2019/10/18/5-3-release-email/)).

**Comment by francescamarano** [comment]
Can you quantify how long it takes you to do this?
I think beside Dev Notes you also include feedback from maintainers?

**Comment by jeffpaul** [comment]
My process going back a couple years/releases essentially breaks down to:
- Copy previous release Field Guide, rename and update copy to current release version number
- Update all links to point to current release version number
- Remove previously embedded dev notes
- As new dev notes for the current release cycle get published, embed them in the respective section of the Field Guide
- Update the Field Guide heading with the major focuses from the release
- Update section listings to relate to areas receiving dev notes
- Add/update section summary pulling major highlights from embedded dev notes to help developers know whether those dev notes are relevant to them or not
- Each Component team is sent a group direct message in Slack, pulling the list of maintainers from the [individual component pages](https://make.wordpress.org/core/components/):
> It’s that time again `Component Name` component maintainers… are there any tickets in the X.Y release that you’d like called out in the Field Guide that aren’t already included in a Dev Note?  As a reference, here are the ## tickets currently in the milestone for you: https://core.trac.wordpress.org/query?component=ComponentName&milestone=X.Y&col=id&col=summary&col=milestone&col=owner&col=type&col=status&col=priority&order=priority.  Note that we intend to publish the Field Guide <timeline>, so the sooner you can respond the better… thanks!
- The responses are added into the `But Wait, There is More!` section of the Field Guide as individual bullet items in the format of:
> * Component Name: Trac Ticket Summary (#Trac Ticket Number)

I'll then generally look for at least one reviewer from the release squad, but ideally one technical review and one marketing/copy review.  From there it's published with the version number "X-Y" and "field-guide" tags.

After that gets published, I'll jump into the Plugin Review Team's make site (see link in my comment above) though you can just as easily ping the Plugin Review team reps for help.  There's a quick post on their make site scripting the email to plugin authors, a quick review from the team reps, and then it gets sent out.

**Comment by jeffpaul** [comment]
I usually start the draft Field Guide doc early in the release process and embed dev notes into it as they get published.  Then a couple days before RC1 I'll block out 2-4 hours to work on copy, formatting, link updating, etc. to get my first real draft of the Field Guide ready.  I usually send the Slack direct messages to component maintainers around this same time frame and give them all ~3 days to send me feedback that I add as bullet points to the `But Wait, There Is More` section.  Once those have all been added it's time for the Field Guide to get that 1-2 reviews from the release squad.

**Comment by kittenkamala** [comment]
Copy previous release Field Guide, rename and update copy to current release version number <--- Can we create a reusable template for this?

As new dev notes for the current release cycle get published, embed them in the respective section of the Field Guide <-- Can this be automated with maybe a # tag in the dev notes?

**Comment by kittenkamala** [comment]
Each Component team is sent a group direct message in Slack, pulling the list of maintainers from the individual component pages <--- Would this be faster if something like a google form were used to collect information?

**Comment by jeffpaul** [comment]
@kittenkamala a template Field Guide post could be created, but doesn't save all that much time from copying the previous version.

I don't think we'd want to rely on a # tag to pull dev notes automatically into the Field Guide as the section wherein they're placed depends on their content, much likely better that we just add those manually.

As for the messaging component maintainers, I don't think a Google Form speeds anything up at if anything adding another tool to the workflow probably slows things down.

**Comment by jeffpaul** [comment]
Note that I've gone ahead and pulled this into an initial Make/Core handbook page here: https://make.wordpress.org/core/handbook/tutorials/publishing-the-field-guide/.  I suggest we close out this issue and work on iterating the documentation in the handbook.

**Comment by francescamarano** [comment]
The handbook page is live! Thank you @jeffpaul
