### ISSUE TITLE
Examine existing documentation in-depth

### ISSUE THREAD

**Issue by kittenkamala** [francescamarano/release-model-wg#4]
Existing handbook documentation on the release cycle needs an in-depth review. Some things that should be examined are: 
- items that are out of date 
- contingent on other steps
- should be tied to particular timeframes
- can be automated

**Comment by francescamarano** [comment]
Duplicate? https://github.com/francescamarano/release-model-wg/issues/2

**Comment by kittenkamala** [comment]
Yes :) We can probably close this one.
